# Generated by Django 5.0.7 on 2024-07-11 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст'),
        ),
    ]
